# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from ._hooks import HookResult, Hooks
    from . import _models as models


class BoundaryMixin:
    """Schema-derived named boundaries; implemented by Hooks.dispatch."""

    async def config_change_after(
        self, input: models.ConfigChangeAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "config.change.after", input, **kwargs
        )

    async def config_change_before(
        self, input: models.ConfigChangeBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "config.change.before", input, **kwargs
        )

    async def context_compact_after(
        self, input: models.ContextCompactAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "context.compact.after", input, **kwargs
        )

    async def context_compact_before(
        self, input: models.ContextCompactBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "context.compact.before", input, **kwargs
        )

    async def file_changed(
        self, input: models.FileChangedInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("file.changed", input, **kwargs)

    async def hook_failure(
        self, input: models.HookFailureInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("hook.failure", input, **kwargs)

    async def model_error(
        self, input: models.ModelErrorInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("model.error", input, **kwargs)

    async def model_request_before(
        self, input: models.ModelRequestBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "model.request.before", input, **kwargs
        )

    async def model_response_after(
        self, input: models.ModelResponseAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "model.response.after", input, **kwargs
        )

    async def model_switch_after(
        self, input: models.ModelSwitchAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("model.switch.after", input, **kwargs)

    async def model_switch_before(
        self, input: models.ModelSwitchBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "model.switch.before", input, **kwargs
        )

    async def session_end(
        self, input: models.SessionEndInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("session.end", input, **kwargs)

    async def session_start(
        self, input: models.SessionStartInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("session.start", input, **kwargs)

    async def task_change_after(
        self, input: models.TaskChangeAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("task.change.after", input, **kwargs)

    async def task_change_before(
        self, input: models.TaskChangeBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("task.change.before", input, **kwargs)

    async def tool_after(
        self, input: models.ToolAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("tool.after", input, **kwargs)

    async def tool_batch_after(
        self, input: models.ToolBatchAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("tool.batch.after", input, **kwargs)

    async def tool_before(
        self, input: models.ToolBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("tool.before", input, **kwargs)

    async def tool_permission_request(
        self, input: models.ToolPermissionRequestInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "tool.permission.request", input, **kwargs
        )

    async def tool_permission_resolved(
        self, input: models.ToolPermissionResolvedInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "tool.permission.resolved", input, **kwargs
        )

    async def tool_progress(
        self, input: models.ToolProgressInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("tool.progress", input, **kwargs)

    async def turn_end(
        self, input: models.TurnEndInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("turn.end", input, **kwargs)

    async def turn_finish_before(
        self, input: models.TurnFinishBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("turn.finish.before", input, **kwargs)

    async def turn_progress(
        self, input: models.TurnProgressInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("turn.progress", input, **kwargs)

    async def turn_start(
        self, input: models.TurnStartInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("turn.start", input, **kwargs)

    async def user_attention(
        self, input: models.UserAttentionInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch("user.attention", input, **kwargs)

    async def user_elicitation_request(
        self, input: models.UserElicitationRequestInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "user.elicitation.request", input, **kwargs
        )

    async def user_elicitation_result(
        self, input: models.UserElicitationResultInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "user.elicitation.result", input, **kwargs
        )

    async def user_message_inbound(
        self, input: models.UserMessageInboundInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "user.message.inbound", input, **kwargs
        )

    async def user_message_outbound(
        self, input: models.UserMessageOutboundInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "user.message.outbound", input, **kwargs
        )

    async def workspace_change_after(
        self, input: models.WorkspaceChangeAfterInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "workspace.change.after", input, **kwargs
        )

    async def workspace_change_before(
        self, input: models.WorkspaceChangeBeforeInput | dict[str, Any], **kwargs: Any
    ) -> HookResult:
        return await cast("Hooks", self).dispatch(
            "workspace.change.before", input, **kwargs
        )
