# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import Any
from enum import StrEnum
from copy import deepcopy
import json

_UNSET: Any = object()


class Mode(StrEnum):
    INTERCEPT = "intercept"
    OBSERVE = "observe"


class Allow(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["allow"]
        self.update(details)


class Ask(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["ask"]
        self.update(details)


class Deny(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["deny"]
        self.update(details)


class Flow(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self,
        *,
        continuation_count: int = _UNSET,
        max_continuations: int = _UNSET,
        operations: list[Any],
        remaining_continuations: int = _UNSET,
        **extra: Any,
    ) -> None:
        super().__init__(extra)
        if continuation_count is not _UNSET:
            self["continuationCount"] = continuation_count
        if max_continuations is not _UNSET:
            self["maxContinuations"] = max_continuations
        self["operations"] = operations
        if remaining_continuations is not _UNSET:
            self["remainingContinuations"] = remaining_continuations
        details = dict(self)
        self.clear()
        self["effects"] = ["flow"]
        self["flow"] = details


class Message(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["message"]
        self.update(details)


class Return(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["return"]
        self.update(details)


class ElicitationForm(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = []
        self["elicitation"] = {"form": details}


class ElicitationUrl(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = []
        self["elicitation"] = {"url": details}


class InjectContext(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, append: bool = _UNSET, deliver_at: list[Any], **extra: Any
    ) -> None:
        super().__init__(extra)
        self["append"] = json.loads("true") if append is _UNSET else append
        self["deliverAt"] = deliver_at
        details = dict(self)
        self.clear()
        self["effects"] = ["inject"]
        self["inject"] = {"context": details}


class ModifyContent(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"content": details}


class ModifyInput(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"input": details}


class ModifyInstructions(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"instructions": details}


class ModifyOutput(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"output": details}


class ModifyPrompt(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"prompt": details}


class ModifyRequest(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"request": details}


class ModifyResponse(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"response": details}


class ModifySummary(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"summary": details}


class ModifyWorkspace(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"workspace": details}


def _merge(left: dict[str, Any], right: dict[str, Any]) -> None:
    for key, value in right.items():
        if key not in left:
            left[key] = deepcopy(value)
        elif isinstance(left[key], dict) and isinstance(value, dict):
            _merge(left[key], value)
        elif isinstance(left[key], list) and isinstance(value, list):
            left[key].extend(deepcopy(item) for item in value if item not in left[key])
        elif isinstance(left[key], bool) and isinstance(value, bool):
            left[key] = left[key] or value
        elif left[key] != value:
            raise ValueError(f"Conflicting capability grant: {key}")


class Declaration(dict[str, Any]):
    """Explicit delivery modes plus typed or canonical grant fragments.

    No mode, effect, form, or URL authority is inferred from another dimension.
    The canonical dictionary form remains accepted by Hooks without this helper.
    """

    def __init__(
        self, *, modes: list[Mode | str], grants: list[dict[str, Any]], **extra: Any
    ) -> None:
        capabilities: dict[str, Any] = {"effects": []}
        for grant in grants:
            _merge(capabilities, grant)
        super().__init__(extra)
        self["modes"] = list(modes)
        self["capabilities"] = capabilities


__all__ = [
    "Declaration",
    "Mode",
    "Allow",
    "Ask",
    "Deny",
    "Flow",
    "Message",
    "Return",
    "ElicitationForm",
    "ElicitationUrl",
    "InjectContext",
    "ModifyContent",
    "ModifyInput",
    "ModifyInstructions",
    "ModifyOutput",
    "ModifyPrompt",
    "ModifyRequest",
    "ModifyResponse",
    "ModifySummary",
    "ModifyWorkspace",
]
