# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import Any
from enum import StrEnum
from copy import deepcopy
import json

_UNSET: Any = object()


class Mode(StrEnum):
    INTERCEPT = "intercept"
    OBSERVE = "observe"


class Allow(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["allow"]
        self.update(details)


class Ask(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["ask"]
        self.update(details)


class Deny(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["deny"]
        self.update(details)


class Flow(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self,
        *,
        continuation_count: int = _UNSET,
        max_continuations: int = _UNSET,
        operations: list[Any],
        remaining_continuations: int = _UNSET,
        **extra: Any,
    ) -> None:
        super().__init__(extra)
        if continuation_count is not _UNSET:
            self["continuationCount"] = continuation_count
        if max_continuations is not _UNSET:
            self["maxContinuations"] = max_continuations
        self["operations"] = operations
        if remaining_continuations is not _UNSET:
            self["remainingContinuations"] = remaining_continuations
        details = dict(self)
        self.clear()
        self["effects"] = ["flow"]
        self["flow"] = details


class Message(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["message"]
        self.update(details)


class Return(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = ["return"]
        self.update(details)


class ElicitationForm(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = []
        self["elicitation"] = {"form": details}


class ElicitationUrl(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(self, **extra: Any) -> None:
        super().__init__(extra)
        details = dict(self)
        self.clear()
        self["effects"] = []
        self["elicitation"] = {"url": details}


class InjectContext(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, append: bool = _UNSET, deliver_at: list[Any], **extra: Any
    ) -> None:
        super().__init__(extra)
        self["append"] = json.loads("true") if append is _UNSET else append
        self["deliverAt"] = deliver_at
        details = dict(self)
        self.clear()
        self["effects"] = ["inject"]
        self["inject"] = {"context": details}


class ModifyContent(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"content": details}


class ModifyInput(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"input": details}


class ModifyInstructions(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"instructions": details}


class ModifyOutput(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"output": details}


class ModifyPrompt(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"prompt": details}


class ModifyRequest(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"request": details}


class ModifyResponse(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"response": details}


class ModifySummary(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"summary": details}


class ModifyWorkspace(dict[str, Any]):
    """Keyword-only wire object; parsing remains strict and separate."""

    def __init__(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET, **extra: Any
    ) -> None:
        super().__init__(extra)
        self["merge"] = json.loads("false") if merge is _UNSET else merge
        self["replace"] = json.loads("false") if replace is _UNSET else replace
        details = dict(self)
        self.clear()
        self["effects"] = ["modify"]
        self["modify"] = {"workspace": details}


def _merge(left: dict[str, Any], right: dict[str, Any]) -> None:
    for key, value in right.items():
        if key not in left:
            left[key] = deepcopy(value)
        elif isinstance(left[key], dict) and isinstance(value, dict):
            _merge(left[key], value)
        elif isinstance(left[key], list) and isinstance(value, list):
            left[key].extend(deepcopy(item) for item in value if item not in left[key])
        elif isinstance(left[key], bool) and isinstance(value, bool):
            left[key] = left[key] or value
        elif left[key] != value:
            raise ValueError(f"Conflicting capability grant: {key}")


class Declaration(dict[str, Any]):
    """Explicit delivery modes plus typed or canonical grant fragments.

    No mode, effect, form, or URL authority is inferred from another dimension.
    The canonical dictionary form remains accepted by Hooks without this helper.
    """

    def __init__(
        self, *, modes: list[Mode | str], grants: list[dict[str, Any]], **extra: Any
    ) -> None:
        capabilities: dict[str, Any] = {"effects": []}
        for grant in grants:
            _merge(capabilities, grant)
        super().__init__(extra)
        self["modes"] = list(modes)
        self["capabilities"] = capabilities


class Builder:
    """Immutable declaration; intercept deliberately supports observation too.

    Grants describe host support, not evidence that the host enacted effects.
    Raw Declaration remains available without convenience inference.
    """

    __slots__ = ("_modes", "_capabilities")

    def __init__(self, modes: tuple[Mode, ...], capabilities: dict[str, Any]) -> None:
        object.__setattr__(self, "_modes", modes)
        object.__setattr__(self, "_capabilities", json.dumps(capabilities))

    def __setattr__(self, name: str, value: Any) -> None:
        raise AttributeError("Capability builders are immutable")

    def to_wire(self) -> dict[str, Any]:
        capabilities = json.loads(self._capabilities)
        if Mode.INTERCEPT in self._modes and capabilities == {"effects": []}:
            raise ValueError("Intercept declarations require an explicit grant")
        return {"modes": list(self._modes), "capabilities": capabilities}

    def _add(self, grant: dict[str, Any]) -> Builder:
        if grant.get("effects") and Mode.INTERCEPT not in self._modes:
            raise ValueError("Observation-only declarations cannot grant effects")
        capabilities = json.loads(self._capabilities)
        _merge(capabilities, grant)
        return Builder(self._modes, capabilities)

    def allow(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(Allow(**arguments))

    def ask(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(Ask(**arguments))

    def deny(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(Deny(**arguments))

    def flow(
        self,
        *,
        continuation_count: int = _UNSET,
        max_continuations: int = _UNSET,
        operations: list[Any],
        remaining_continuations: int = _UNSET,
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if continuation_count is not _UNSET:
            arguments["continuation_count"] = continuation_count
            if (
                type(continuation_count) is not int
                or not 0 <= continuation_count <= 9007199254740991
            ):
                raise ValueError(
                    "continuation counts must be nonnegative safe integers"
                )
        if max_continuations is not _UNSET:
            arguments["max_continuations"] = max_continuations
            if (
                type(max_continuations) is not int
                or not 0 <= max_continuations <= 9007199254740991
            ):
                raise ValueError(
                    "continuation counts must be nonnegative safe integers"
                )
        if operations is not _UNSET:
            arguments["operations"] = operations
            if not operations or any(
                value not in ["continue", "stop"] for value in operations
            ):
                raise ValueError("operations requires known, nonempty values")
        if remaining_continuations is not _UNSET:
            arguments["remaining_continuations"] = remaining_continuations
            if (
                type(remaining_continuations) is not int
                or not 0 <= remaining_continuations <= 9007199254740991
            ):
                raise ValueError(
                    "continuation counts must be nonnegative safe integers"
                )
        if "continue" in operations and (
            remaining_continuations is _UNSET or continuation_count is _UNSET
        ):
            raise ValueError(
                "continue requires remaining_continuations and continuation_count"
            )
        return self._add(Flow(**arguments))

    def message(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(Message(**arguments))

    def return_2(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(Return(**arguments))

    def elicitation_form(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(ElicitationForm(**arguments))

    def elicitation_url(self) -> Builder:
        arguments: dict[str, Any] = {}
        return self._add(ElicitationUrl(**arguments))

    def inject_context(
        self, *, append: bool = _UNSET, deliver_at: list[Any]
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if append is not _UNSET:
            arguments["append"] = append
            if append is not True:
                raise ValueError("append must be true")
        if deliver_at is not _UNSET:
            arguments["deliver_at"] = deliver_at
            if not deliver_at or any(
                value not in ["next_turn", "now"] for value in deliver_at
            ):
                raise ValueError("deliver_at requires known, nonempty values")
        return self._add(InjectContext(**arguments))

    def modify_content(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyContent(**arguments))

    def modify_input(self, *, merge: bool = _UNSET, replace: bool = _UNSET) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyInput(**arguments))

    def modify_instructions(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyInstructions(**arguments))

    def modify_output(self, *, merge: bool = _UNSET, replace: bool = _UNSET) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyOutput(**arguments))

    def modify_prompt(self, *, merge: bool = _UNSET, replace: bool = _UNSET) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyPrompt(**arguments))

    def modify_request(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyRequest(**arguments))

    def modify_response(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyResponse(**arguments))

    def modify_summary(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifySummary(**arguments))

    def modify_workspace(
        self, *, merge: bool = _UNSET, replace: bool = _UNSET
    ) -> Builder:
        arguments: dict[str, Any] = {}
        if merge is not _UNSET:
            arguments["merge"] = merge
            if not isinstance(merge, bool):
                raise ValueError("merge must be boolean")
        if replace is not _UNSET:
            arguments["replace"] = replace
            if not isinstance(replace, bool):
                raise ValueError("replace must be boolean")
        if not (merge is True or replace is True):
            raise ValueError("Select at least one operation")
        return self._add(ModifyWorkspace(**arguments))


def intercept() -> Builder:
    """Advertise both intercept and observe delivery, with explicit grants."""
    return Builder((Mode.INTERCEPT, Mode.OBSERVE), {"effects": []})


def observe() -> Builder:
    """Advertise observation only; no effect authority is inferred."""
    return Builder((Mode.OBSERVE,), {"effects": []})


__all__ = [
    "Declaration",
    "Mode",
    "Allow",
    "Ask",
    "Deny",
    "Flow",
    "Message",
    "Return",
    "ElicitationForm",
    "ElicitationUrl",
    "InjectContext",
    "ModifyContent",
    "ModifyInput",
    "ModifyInstructions",
    "ModifyOutput",
    "ModifyPrompt",
    "ModifyRequest",
    "ModifyResponse",
    "ModifySummary",
    "ModifyWorkspace",
    "Builder",
    "intercept",
    "observe",
]
