# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import Any
from .state import Candidate as Candidate, Provenance as Provenance


def value(value: Any, *, provenance: Provenance | None = None) -> Candidate:
    if provenance is None:
        return Candidate(value=value)
    return Candidate(value=value, provenance=provenance)
