# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from ._models import (
    McpElicitationElicitRequestFormParamsRequestedSchema as RequestedSchema,
)
from dataclasses import dataclass as _dataclass, field as _field
from typing import Any, Generic, TypeVar
from . import _models
from .generated import JsonValue

T = TypeVar("T")
P = TypeVar("P")


@_dataclass(kw_only=True)
class Candidate(Generic[T, P]):
    """Schema-derived projection of ToolCandidate; codecs remain runtime-owned."""

    provenance: P = _field(default=_models._UNSET)
    value: T
    additional_properties: dict[str, JsonValue] = _field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = dict(self.additional_properties)
        if self.provenance is not _models._UNSET:
            result["provenance"] = self.provenance
        else:
            result.pop("provenance", None)
        result["value"] = self.value
        return result


@_dataclass(kw_only=True)
class ElicitResult(Generic[T]):
    """Schema-derived projection of McpElicitationElicitResult; codecs remain runtime-owned."""

    meta: dict[str, Any] = _field(default=_models._UNSET)
    action: str
    content: T = _field(default=_models._UNSET)
    additional_properties: dict[str, JsonValue] = _field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = dict(self.additional_properties)
        if self.meta is not _models._UNSET:
            result["_meta"] = self.meta
        else:
            result.pop("_meta", None)
        result["action"] = self.action
        if self.content is not _models._UNSET:
            result["content"] = self.content
        else:
            result.pop("content", None)
        return result


__all__ = ["Candidate", "ElicitResult", "RequestedSchema"]
