# Generated by ahp-codegen. DO NOT EDIT.
from enum import StrEnum


class Code(StrEnum):
    PROTOCOL_REJECTION = "protocol_rejection"
    REMOTE_RPC = "remote_rpc"
    TRANSPORT = "transport"
    CANCELLED = "cancelled"
    DEADLINE_EXCEEDED = "deadline_exceeded"
    PREPARATION = "preparation"
    CAPACITY = "capacity"


DiagnosticCode = Code
