# Generated by ahp-codegen. DO NOT EDIT.
from typing import Literal
from . import _models
from ._grants import EffectName as EffectName
from ._models.effect import Allow as Allow
from ._models.effect import AllowEffect as AllowEffect
from ._models.effect import Ask as Ask
from ._models.effect import AskEffect as AskEffect
from ._models.effect import ContextCompactAfterModify as ContextCompactAfterModify
from ._models.effect import (
    ContextCompactAfterModifyEffect as ContextCompactAfterModifyEffect,
)
from ._models.effect import ContextCompactBeforeModify as ContextCompactBeforeModify
from ._models.effect import (
    ContextCompactBeforeModifyEffect as ContextCompactBeforeModifyEffect,
)
from ._models.effect import ContinueFlow as ContinueFlow
from ._models.effect import ContinueFlowEffect as ContinueFlowEffect
from ._models.effect import DeliverAt as DeliverAt
from ._models.effect import Deny as Deny
from ._models.effect import DenyEffect as DenyEffect
from ._models.effect import Extensions as Extensions
from ._models.effect import Inject as Inject
from ._models.effect import InjectEffect as InjectEffect
from ._models.effect import Message as Message
from ._models.effect import MessageEffect as MessageEffect
from ._models.effect import ModelRequestBeforeModify as ModelRequestBeforeModify
from ._models.effect import (
    ModelRequestBeforeModifyEffect as ModelRequestBeforeModifyEffect,
)
from ._models.effect import ModelResponseAfterModify as ModelResponseAfterModify
from ._models.effect import (
    ModelResponseAfterModifyEffect as ModelResponseAfterModifyEffect,
)
from ._models.effect import ModifyForm as ModifyForm
from ._models.effect import ModifyFormEffect as ModifyFormEffect
from ._models.effect import ModifyInput as ModifyInput
from ._models.effect import ModifyInputEffect as ModifyInputEffect
from ._models.effect import ModifyMessages as ModifyMessages
from ._models.effect import ModifyMessagesEffect as ModifyMessagesEffect
from ._models.effect import ModifyText as ModifyText
from ._models.effect import ModifyTextEffect as ModifyTextEffect
from ._models.effect import ModifyWorkspace as ModifyWorkspace
from ._models.effect import ModifyWorkspaceEffect as ModifyWorkspaceEffect
from ._models.effect import ReturnElicitResult as ReturnElicitResult
from ._models.effect import ReturnElicitResultEffect as ReturnElicitResultEffect
from ._models.effect import ReturnMessages as ReturnMessages
from ._models.effect import ReturnMessagesEffect as ReturnMessagesEffect
from ._models.effect import ReturnText as ReturnText
from ._models.effect import ReturnTextEffect as ReturnTextEffect
from ._models.effect import ReturnTool as ReturnTool
from ._models.effect import ReturnToolEffect as ReturnToolEffect
from ._models.effect import StopFlow as StopFlow
from ._models.effect import StopFlowEffect as StopFlowEffect
from ._models.effect import ToolAfterModify as ToolAfterModify
from ._models.effect import ToolAfterModifyEffect as ToolAfterModifyEffect
from ._models.effect import ToolBeforeModify as ToolBeforeModify
from ._models.effect import ToolBeforeModifyEffect as ToolBeforeModifyEffect
from ._models.effect import ToolPermissionRequestModify as ToolPermissionRequestModify
from ._models.effect import (
    ToolPermissionRequestModifyEffect as ToolPermissionRequestModifyEffect,
)
from ._models.effect import TurnFinishBeforeModify as TurnFinishBeforeModify
from ._models.effect import TurnFinishBeforeModifyEffect as TurnFinishBeforeModifyEffect
from ._models.effect import TurnStartModify as TurnStartModify
from ._models.effect import TurnStartModifyEffect as TurnStartModifyEffect
from ._models.effect import UserElicitationResultModify as UserElicitationResultModify
from ._models.effect import (
    UserElicitationResultModifyEffect as UserElicitationResultModifyEffect,
)
from ._models.effect import UserMessageInboundModify as UserMessageInboundModify
from ._models.effect import (
    UserMessageInboundModifyEffect as UserMessageInboundModifyEffect,
)
from ._models.effect import UserMessageOutboundModify as UserMessageOutboundModify
from ._models.effect import (
    UserMessageOutboundModifyEffect as UserMessageOutboundModifyEffect,
)
from ._models.effect import WorkspaceChangeBeforeModify as WorkspaceChangeBeforeModify
from ._models.effect import (
    WorkspaceChangeBeforeModifyEffect as WorkspaceChangeBeforeModifyEffect,
)

from typing import Any
from ._models import _UNSET


def merge_content_form(
    value: dict[str, bool | float | list[str] | str],
) -> _models.ModifyFormEffect:
    return _models.ModifyFormEffect(target="content", operation="merge", value=value)


def replace_content_form(
    value: dict[str, bool | float | list[str] | str],
) -> _models.ModifyFormEffect:
    return _models.ModifyFormEffect(target="content", operation="replace", value=value)


def merge_input(value: dict[str, Any]) -> _models.ModifyInputEffect:
    return _models.ModifyInputEffect(target="input", operation="merge", value=value)


def replace_input(value: dict[str, Any]) -> _models.ModifyInputEffect:
    return _models.ModifyInputEffect(target="input", operation="replace", value=value)


def merge_content(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="content", operation="merge", value=value
    )


def replace_content(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="content", operation="replace", value=value
    )


def merge_output(value: list[_models.CanonicalMessage]) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(target="output", operation="merge", value=value)


def replace_output(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="output", operation="replace", value=value
    )


def merge_prompt(value: list[_models.CanonicalMessage]) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(target="prompt", operation="merge", value=value)


def replace_prompt(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="prompt", operation="replace", value=value
    )


def merge_request(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="request", operation="merge", value=value
    )


def replace_request(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="request", operation="replace", value=value
    )


def merge_response(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="response", operation="merge", value=value
    )


def replace_response(
    value: list[_models.CanonicalMessage],
) -> _models.ModifyMessagesEffect:
    return _models.ModifyMessagesEffect(
        target="response", operation="replace", value=value
    )


def merge_instructions(
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> _models.ModifyTextEffect:
    return _models.ModifyTextEffect(
        target="instructions", operation="merge", value=value
    )


def replace_instructions(
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> _models.ModifyTextEffect:
    return _models.ModifyTextEffect(
        target="instructions", operation="replace", value=value
    )


def merge_summary(
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> _models.ModifyTextEffect:
    return _models.ModifyTextEffect(target="summary", operation="merge", value=value)


def replace_summary(
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> _models.ModifyTextEffect:
    return _models.ModifyTextEffect(target="summary", operation="replace", value=value)


def merge_workspace(value: _models.WorkspaceChange) -> _models.ModifyWorkspaceEffect:
    return _models.ModifyWorkspaceEffect(
        target="workspace", operation="merge", value=value
    )


def replace_workspace(value: _models.WorkspaceChange) -> _models.ModifyWorkspaceEffect:
    return _models.ModifyWorkspaceEffect(
        target="workspace", operation="replace", value=value
    )


def allow() -> Allow:
    return Allow()


def ask() -> Ask:
    return Ask()


def context_compact_after_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> ContextCompactAfterModify:
    return ContextCompactAfterModify(operation=operation, value=value)


modify_summary = context_compact_after_modify


def context_compact_before_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> ContextCompactBeforeModify:
    return ContextCompactBeforeModify(operation=operation, value=value)


modify_instructions = context_compact_before_modify


def continue_flow(
    *,
    instruction: str = _UNSET,
) -> ContinueFlow:
    return ContinueFlow(instruction=instruction)


flow_continue = continue_flow


def inject(
    *,
    deliver_at: str,
    value: list[_models.CanonicalMessage],
) -> Inject:
    return Inject(deliver_at=deliver_at, value=value)


inject_context_append = inject


def message(
    *,
    text: str,
) -> Message:
    return Message(text=text)


def model_request_before_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> ModelRequestBeforeModify:
    return ModelRequestBeforeModify(operation=operation, value=value)


modify_request = model_request_before_modify


def model_response_after_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> ModelResponseAfterModify:
    return ModelResponseAfterModify(operation=operation, value=value)


modify_response = model_response_after_modify


def modify_form(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: dict[str, bool | float | list[str] | str],
) -> ModifyForm:
    return ModifyForm(operation=operation, value=value)


modify_content = modify_form


def modify_input(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: dict[str, Any],
) -> ModifyInput:
    return ModifyInput(operation=operation, value=value)


def modify_messages(
    *,
    operation: Literal["merge"] | Literal["replace"],
    target: Literal["content"]
    | Literal["output"]
    | Literal["prompt"]
    | Literal["request"]
    | Literal["response"],
    value: list[_models.CanonicalMessage],
) -> ModifyMessages:
    return ModifyMessages(operation=operation, target=target, value=value)


modify = modify_messages


def modify_text(
    *,
    operation: Literal["merge"] | Literal["replace"],
    target: Literal["instructions"] | Literal["summary"],
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> ModifyText:
    return ModifyText(operation=operation, target=target, value=value)


def modify_workspace(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: _models.WorkspaceChange,
) -> ModifyWorkspace:
    return ModifyWorkspace(operation=operation, value=value)


def return_elicit_result(
    *,
    value: _models.McpElicitationElicitResult,
) -> ReturnElicitResult:
    return ReturnElicitResult(value=value)


def return_messages(
    *,
    value: list[_models.CanonicalMessage],
) -> ReturnMessages:
    return ReturnMessages(value=value)


def return_text(
    *,
    value: list[
        _models.TextBodyPart
        | _models.TextGapPart
        | _models.TextMetadataPart
        | _models.TextOmittedPart
    ],
) -> ReturnText:
    return ReturnText(value=value)


def return_tool(
    *,
    value: Any,
) -> ReturnTool:
    return ReturnTool(value=value)


return_ = return_tool


def stop_flow(
    *,
    reason: str,
) -> StopFlow:
    return StopFlow(reason=reason)


flow_stop = stop_flow


def tool_after_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> ToolAfterModify:
    return ToolAfterModify(operation=operation, value=value)


modify_output = tool_after_modify


def tool_before_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: dict[str, Any],
) -> ToolBeforeModify:
    return ToolBeforeModify(operation=operation, value=value)


def tool_permission_request_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: dict[str, Any],
) -> ToolPermissionRequestModify:
    return ToolPermissionRequestModify(operation=operation, value=value)


def turn_finish_before_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> TurnFinishBeforeModify:
    return TurnFinishBeforeModify(operation=operation, value=value)


def turn_start_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> TurnStartModify:
    return TurnStartModify(operation=operation, value=value)


modify_prompt = turn_start_modify


def user_elicitation_result_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: dict[str, bool | float | list[str] | str],
) -> UserElicitationResultModify:
    return UserElicitationResultModify(operation=operation, value=value)


def user_message_inbound_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> UserMessageInboundModify:
    return UserMessageInboundModify(operation=operation, value=value)


def user_message_outbound_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: list[_models.CanonicalMessage],
) -> UserMessageOutboundModify:
    return UserMessageOutboundModify(operation=operation, value=value)


def workspace_change_before_modify(
    *,
    operation: Literal["merge"] | Literal["replace"],
    value: _models.WorkspaceChange,
) -> WorkspaceChangeBeforeModify:
    return WorkspaceChangeBeforeModify(operation=operation, value=value)


deny = Deny
