# Generated by ahp-codegen. DO NOT EDIT.
from ._models.event import CallsItem as CallsItem
from ._models.event import CallsItemBatch as CallsItemBatch
from ._models.event import CallsItemCall as CallsItemCall
from ._models.event import CallsItemOutcome as CallsItemOutcome
from ._models.event import CallsItemTool as CallsItemTool
from ._models.event import ChangesItem as ChangesItem
from ._models.event import ChangesItemOperation as ChangesItemOperation
from ._models.event import ConfigChangeAfter as ConfigChangeAfter
from ._models.event import ConfigChangeAfterEvent as ConfigChangeAfterEvent
from ._models.event import ConfigChangeAfterInput as ConfigChangeAfterInput
from ._models.event import ConfigChangeBefore as ConfigChangeBefore
from ._models.event import ConfigChangeBeforeEvent as ConfigChangeBeforeEvent
from ._models.event import ConfigChangeBeforeInput as ConfigChangeBeforeInput
from ._models.event import ContextCompactAfter as ContextCompactAfter
from ._models.event import ContextCompactAfterEvent as ContextCompactAfterEvent
from ._models.event import ContextCompactAfterInput as ContextCompactAfterInput
from ._models.event import ContextCompactBefore as ContextCompactBefore
from ._models.event import ContextCompactBeforeEvent as ContextCompactBeforeEvent
from ._models.event import ContextCompactBeforeInput as ContextCompactBeforeInput
from ._models.event import DecidedBy as DecidedBy
from ._models.event import Decision as Decision
from ._models.event import Delta as Delta
from ._models.event import Event as Event
from ._models.event import ExecutionExecuted as ExecutionExecuted
from ._models.event import ExecutionSkippedCancelled as ExecutionSkippedCancelled
from ._models.event import ExecutionSkippedOther as ExecutionSkippedOther
from ._models.event import ExecutionSkippedPolicy as ExecutionSkippedPolicy
from ._models.event import (
    ExecutionSkippedSuppliedResult as ExecutionSkippedSuppliedResult,
)
from ._models.event import ExecutionSkippedTimeout as ExecutionSkippedTimeout
from ._models.event import FileChanged as FileChanged
from ._models.event import FileChangedEvent as FileChangedEvent
from ._models.event import FileChangedInput as FileChangedInput
from ._models.event import HookFailure as HookFailure
from ._models.event import HookFailureEvent as HookFailureEvent
from ._models.event import HookFailureInput as HookFailureInput
from ._models.event import Item as Item
from ._models.event import Manifest as Manifest
from ._models.event import ModelError as ModelError
from ._models.event import ModelErrorEvent as ModelErrorEvent
from ._models.event import ModelErrorInput as ModelErrorInput
from ._models.event import ModelRequestBefore as ModelRequestBefore
from ._models.event import ModelRequestBeforeEvent as ModelRequestBeforeEvent
from ._models.event import ModelRequestBeforeInput as ModelRequestBeforeInput
from ._models.event import ModelResponseAfter as ModelResponseAfter
from ._models.event import ModelResponseAfterEvent as ModelResponseAfterEvent
from ._models.event import ModelResponseAfterInput as ModelResponseAfterInput
from ._models.event import ModelSwitchAfter as ModelSwitchAfter
from ._models.event import ModelSwitchAfterEvent as ModelSwitchAfterEvent
from ._models.event import ModelSwitchAfterInput as ModelSwitchAfterInput
from ._models.event import ModelSwitchBefore as ModelSwitchBefore
from ._models.event import ModelSwitchBeforeEvent as ModelSwitchBeforeEvent
from ._models.event import ModelSwitchBeforeInput as ModelSwitchBeforeInput
from ._models.event import Params as Params
from ._models.event import PartialOutput as PartialOutput
from ._models.event import Path as Path
from ._models.event import Previous as Previous
from ._models.event import Pricing as Pricing
from ._models.event import Proposed as Proposed
from ._models.event import RemovedItem as RemovedItem
from ._models.event import SessionEnd as SessionEnd
from ._models.event import SessionEndEvent as SessionEndEvent
from ._models.event import SessionEndInput as SessionEndInput
from ._models.event import SessionStart as SessionStart
from ._models.event import SessionStartEvent as SessionStartEvent
from ._models.event import SessionStartInput as SessionStartInput
from ._models.event import SuggestionsItem as SuggestionsItem
from ._models.event import TaskChangeAfter as TaskChangeAfter
from ._models.event import TaskChangeAfterEvent as TaskChangeAfterEvent
from ._models.event import TaskChangeAfterInput as TaskChangeAfterInput
from ._models.event import TaskChangeBefore as TaskChangeBefore
from ._models.event import TaskChangeBeforeEvent as TaskChangeBeforeEvent
from ._models.event import TaskChangeBeforeInput as TaskChangeBeforeInput
from ._models.event import ToolAfter as ToolAfter
from ._models.event import ToolAfterEvent as ToolAfterEvent
from ._models.event import ToolAfterInput as ToolAfterInput
from ._models.event import ToolBatchAfter as ToolBatchAfter
from ._models.event import ToolBatchAfterEvent as ToolBatchAfterEvent
from ._models.event import ToolBatchAfterInput as ToolBatchAfterInput
from ._models.event import ToolBefore as ToolBefore
from ._models.event import ToolBeforeEvent as ToolBeforeEvent
from ._models.event import ToolBeforeInput as ToolBeforeInput
from ._models.event import ToolPermissionRequest as ToolPermissionRequest
from ._models.event import ToolPermissionRequestEvent as ToolPermissionRequestEvent
from ._models.event import ToolPermissionRequestInput as ToolPermissionRequestInput
from ._models.event import ToolPermissionResolved as ToolPermissionResolved
from ._models.event import ToolPermissionResolvedEvent as ToolPermissionResolvedEvent
from ._models.event import ToolPermissionResolvedInput as ToolPermissionResolvedInput
from ._models.event import ToolProgress as ToolProgress
from ._models.event import ToolProgressEvent as ToolProgressEvent
from ._models.event import ToolProgressInput as ToolProgressInput
from ._models.event import TurnEnd as TurnEnd
from ._models.event import TurnEndEvent as TurnEndEvent
from ._models.event import TurnEndInput as TurnEndInput
from ._models.event import TurnFinishBefore as TurnFinishBefore
from ._models.event import TurnFinishBeforeEvent as TurnFinishBeforeEvent
from ._models.event import TurnFinishBeforeInput as TurnFinishBeforeInput
from ._models.event import TurnProgress as TurnProgress
from ._models.event import TurnProgressEvent as TurnProgressEvent
from ._models.event import TurnProgressInput as TurnProgressInput
from ._models.event import TurnStart as TurnStart
from ._models.event import TurnStartEvent as TurnStartEvent
from ._models.event import TurnStartInput as TurnStartInput
from ._models.event import UserAttention as UserAttention
from ._models.event import UserAttentionEvent as UserAttentionEvent
from ._models.event import UserAttentionInput as UserAttentionInput
from ._models.event import UserElicitationRequest as UserElicitationRequest
from ._models.event import UserElicitationRequestEvent as UserElicitationRequestEvent
from ._models.event import UserElicitationRequestInput as UserElicitationRequestInput
from ._models.event import UserElicitationResult as UserElicitationResult
from ._models.event import UserElicitationResultEvent as UserElicitationResultEvent
from ._models.event import UserElicitationResultInput as UserElicitationResultInput
from ._models.event import UserMessageInbound as UserMessageInbound
from ._models.event import UserMessageInboundEvent as UserMessageInboundEvent
from ._models.event import UserMessageInboundInput as UserMessageInboundInput
from ._models.event import UserMessageOutbound as UserMessageOutbound
from ._models.event import UserMessageOutboundEvent as UserMessageOutboundEvent
from ._models.event import UserMessageOutboundInput as UserMessageOutboundInput
from ._models.event import WorkspaceChangeAfter as WorkspaceChangeAfter
from ._models.event import WorkspaceChangeAfterEvent as WorkspaceChangeAfterEvent
from ._models.event import WorkspaceChangeAfterInput as WorkspaceChangeAfterInput
from ._models.event import WorkspaceChangeBefore as WorkspaceChangeBefore
from ._models.event import WorkspaceChangeBeforeEvent as WorkspaceChangeBeforeEvent
from ._models.event import WorkspaceChangeBeforeInput as WorkspaceChangeBeforeInput

from typing import overload, Any
from . import _models


@overload
def response_for_event(
    event: _models.ConfigChangeBeforeEvent,
    response: _models.ConfigChangeBeforeInterceptResponse,
) -> _models.ConfigChangeBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ContextCompactAfterEvent,
    response: _models.ContextCompactAfterInterceptResponse,
) -> _models.ContextCompactAfterInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ContextCompactBeforeEvent,
    response: _models.ContextCompactBeforeInterceptResponse,
) -> _models.ContextCompactBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.Event, response: _models.InterceptResponse
) -> _models.InterceptResponse: ...
@overload
def response_for_event(
    event: _models.ModelRequestBeforeEvent,
    response: _models.ModelRequestBeforeInterceptResponse,
) -> _models.ModelRequestBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ModelResponseAfterEvent,
    response: _models.ModelResponseAfterInterceptResponse,
) -> _models.ModelResponseAfterInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ModelSwitchBeforeEvent,
    response: _models.ModelSwitchBeforeInterceptResponse,
) -> _models.ModelSwitchBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.SessionStartEvent, response: _models.SessionStartInterceptResponse
) -> _models.SessionStartInterceptResponse: ...
@overload
def response_for_event(
    event: _models.TaskChangeBeforeEvent,
    response: _models.TaskChangeBeforeInterceptResponse,
) -> _models.TaskChangeBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ToolAfterEvent, response: _models.ToolAfterInterceptResponse
) -> _models.ToolAfterInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ToolBatchAfterEvent,
    response: _models.ToolBatchAfterInterceptResponse,
) -> _models.ToolBatchAfterInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ToolBeforeEvent, response: _models.ToolBeforeInterceptResponse
) -> _models.ToolBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.ToolPermissionRequestEvent,
    response: _models.ToolPermissionRequestInterceptResponse,
) -> _models.ToolPermissionRequestInterceptResponse: ...
@overload
def response_for_event(
    event: _models.TurnFinishBeforeEvent,
    response: _models.TurnFinishBeforeInterceptResponse,
) -> _models.TurnFinishBeforeInterceptResponse: ...
@overload
def response_for_event(
    event: _models.TurnStartEvent, response: _models.TurnStartInterceptResponse
) -> _models.TurnStartInterceptResponse: ...
@overload
def response_for_event(
    event: _models.UserElicitationRequestEvent,
    response: _models.UserElicitationRequestInterceptResponse,
) -> _models.UserElicitationRequestInterceptResponse: ...
@overload
def response_for_event(
    event: _models.UserElicitationResultEvent,
    response: _models.UserElicitationResultInterceptResponse,
) -> _models.UserElicitationResultInterceptResponse: ...
@overload
def response_for_event(
    event: _models.UserMessageInboundEvent,
    response: _models.UserMessageInboundInterceptResponse,
) -> _models.UserMessageInboundInterceptResponse: ...
@overload
def response_for_event(
    event: _models.UserMessageOutboundEvent,
    response: _models.UserMessageOutboundInterceptResponse,
) -> _models.UserMessageOutboundInterceptResponse: ...
@overload
def response_for_event(
    event: _models.WorkspaceChangeBeforeEvent,
    response: _models.WorkspaceChangeBeforeInterceptResponse,
) -> _models.WorkspaceChangeBeforeInterceptResponse: ...
def response_for_event(event: Any, response: Any) -> Any:
    """Correlate at type-check time only; does not validate the response."""
    return response
