# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import Any, Callable, Literal, Sequence, overload
from . import _models, generated as _wire
from .generated import JsonValue

__all__ = ["ContextualResponse", "response_for_request"]

ContextualResponse = (
    _models.ConfigChangeBeforeInterceptResponse
    | _models.ContextCompactAfterInterceptResponse
    | _models.ContextCompactBeforeInterceptResponse
    | _models.ModelRequestBeforeInterceptResponse
    | _models.ModelResponseAfterInterceptResponse
    | _models.ModelSwitchBeforeInterceptResponse
    | _models.SessionStartInterceptResponse
    | _models.TaskChangeBeforeInterceptResponse
    | _models.ToolAfterInterceptResponse
    | _models.ToolBatchAfterInterceptResponse
    | _models.ToolBeforeInterceptResponse
    | _models.ToolPermissionRequestInterceptResponse
    | _models.TurnFinishBeforeInterceptResponse
    | _models.TurnStartInterceptResponse
    | _models.UserElicitationRequestInterceptResponse
    | _models.UserElicitationResultInterceptResponse
    | _models.UserMessageInboundInterceptResponse
    | _models.UserMessageOutboundInterceptResponse
    | _models.WorkspaceChangeBeforeInterceptResponse
)
_RESPONSE_MODELS: dict[str, Any] = {
    "config.change.before": _models.ConfigChangeBeforeInterceptResponse,
    "context.compact.after": _models.ContextCompactAfterInterceptResponse,
    "context.compact.before": _models.ContextCompactBeforeInterceptResponse,
    "model.request.before": _models.ModelRequestBeforeInterceptResponse,
    "model.response.after": _models.ModelResponseAfterInterceptResponse,
    "model.switch.before": _models.ModelSwitchBeforeInterceptResponse,
    "session.start": _models.SessionStartInterceptResponse,
    "task.change.before": _models.TaskChangeBeforeInterceptResponse,
    "tool.after": _models.ToolAfterInterceptResponse,
    "tool.batch.after": _models.ToolBatchAfterInterceptResponse,
    "tool.before": _models.ToolBeforeInterceptResponse,
    "tool.permission.request": _models.ToolPermissionRequestInterceptResponse,
    "turn.finish.before": _models.TurnFinishBeforeInterceptResponse,
    "turn.start": _models.TurnStartInterceptResponse,
    "user.elicitation.request": _models.UserElicitationRequestInterceptResponse,
    "user.elicitation.result": _models.UserElicitationResultInterceptResponse,
    "user.message.inbound": _models.UserMessageInboundInterceptResponse,
    "user.message.outbound": _models.UserMessageOutboundInterceptResponse,
    "workspace.change.before": _models.WorkspaceChangeBeforeInterceptResponse,
}


@overload
def response_for_request(
    event_type: Literal["config.change.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ConfigChangeBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ConfigChangeBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["context.compact.after"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ContextCompactAfterInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ContextCompactAfterInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["context.compact.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ContextCompactBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ContextCompactBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["model.request.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ModelRequestBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ModelRequestBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["model.response.after"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ModelResponseAfterInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ModelResponseAfterInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["model.switch.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ModelSwitchBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ModelSwitchBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["session.start"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.SessionStartInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.SessionStartInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["task.change.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.TaskChangeBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.TaskChangeBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["tool.after"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ToolAfterInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ToolAfterInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["tool.batch.after"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ToolBatchAfterInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ToolBatchAfterInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["tool.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ToolBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.ToolBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["tool.permission.request"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.ToolPermissionRequestInterceptResponse],
        Sequence[_wire.ParseDiagnostic],
    ]
    | None = None,
) -> _wire.ParseResult[_models.ToolPermissionRequestInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["turn.finish.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.TurnFinishBeforeInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.TurnFinishBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["turn.start"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.TurnStartInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.TurnStartInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["user.elicitation.request"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.UserElicitationRequestInterceptResponse],
        Sequence[_wire.ParseDiagnostic],
    ]
    | None = None,
) -> _wire.ParseResult[_models.UserElicitationRequestInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["user.elicitation.result"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.UserElicitationResultInterceptResponse],
        Sequence[_wire.ParseDiagnostic],
    ]
    | None = None,
) -> _wire.ParseResult[_models.UserElicitationResultInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["user.message.inbound"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.UserMessageInboundInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.UserMessageInboundInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["user.message.outbound"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.UserMessageOutboundInterceptResponse], Sequence[_wire.ParseDiagnostic]
    ]
    | None = None,
) -> _wire.ParseResult[_models.UserMessageOutboundInterceptResponse]: ...
@overload
def response_for_request(
    event_type: Literal["workspace.change.before"],
    raw: str | JsonValue,
    validate: Callable[
        [_models.WorkspaceChangeBeforeInterceptResponse],
        Sequence[_wire.ParseDiagnostic],
    ]
    | None = None,
) -> _wire.ParseResult[_models.WorkspaceChangeBeforeInterceptResponse]: ...
@overload
def response_for_request(
    event_type: str,
    raw: str | JsonValue,
    validate: Callable[[Any], Sequence[_wire.ParseDiagnostic]] | None = None,
) -> _wire.ParseResult[ContextualResponse]: ...
def response_for_request(
    event_type: str,
    raw: str | JsonValue,
    validate: Callable[[Any], Sequence[_wire.ParseDiagnostic]] | None = None,
) -> _wire.ParseResult[Any]:
    """Validate and stage without publication. Unknown events are not authority."""
    model = _RESPONSE_MODELS.get(event_type)
    if model is None:
        return {
            "ok": False,
            "diagnostics": [
                {
                    "path": "",
                    "code": "unknown_variant",
                    "severity": "error",
                    "message": "Unknown request event: " + event_type,
                }
            ],
        }
    cache: dict[Any, Any] = {}
    parsed = _wire._parse_descriptor(_models._DESCRIPTORS[model.__name__], raw, cache)
    if not parsed["ok"]:
        return parsed
    value = model._hydrate_validated(parsed["value"], "", cache)
    diagnostics = list(parsed["diagnostics"])
    if validate is not None:
        diagnostics.extend(validate(value))
    if any(d["severity"] == "error" for d in diagnostics):
        return {"ok": False, "raw": parsed["raw"], "diagnostics": diagnostics}
    return {
        "ok": True,
        "value": value,
        "raw": parsed["raw"],
        "diagnostics": diagnostics,
    }
