# Generated by ahp-codegen. DO NOT EDIT.
from __future__ import annotations
from typing import Any
from ._models import InterceptRequestParamsState as State
from ._models import InterceptRequestParamsStatePermission as Permission
from ._models import InterceptRequestParamsStateFlow as Flow
from ._models import InterceptRequestParamsStateCandidateValueObject as Candidate
from ._models import (
    InterceptRequestParamsStateCandidateValueObjectProvenance as Provenance,
)

_UNSET: Any = object()


def initial(
    permission: Permission,
    *,
    candidate: Candidate | None = None,
    flow: Flow = _UNSET,
    injections: list[Any] = _UNSET,
    instructions: list[str] = _UNSET,
) -> State:
    """Explicit native-hook starting permission, not execution authorization."""
    result = State(permission=Permission(permission), candidate=candidate)
    if flow is not _UNSET:
        result["flow"] = flow
    if injections is not _UNSET:
        result["injections"] = injections
    if instructions is not _UNSET:
        result["instructions"] = instructions
    return result


__all__ = ["State", "Permission", "Candidate", "Provenance", "Flow", "initial"]
